version: 2
updates:
  - package-ecosystem: cargo
    directory: '/'
    schedule:
      interval: monthly
    open-pull-requests-limit: 99
    assignees:
      - ffflorian
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: monthly
    open-pull-requests-limit: 99
    assignees:
      - ffflorian

