version: 2
updates:
  - package-ecosystem: cargo
    directory: '/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 99
    assignees:
      - ffflorian
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 99
    assignees:
      - ffflorian

